config/routes.rb
Rails.application.routes.draw do
  root 'landing_page#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :file_transfers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_transfer.rb
class FileTransfer < ApplicationRecord
  has_many_attached :files
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/file_transfers_controller.rb
class FileTransfersController < ApplicationController
  def index
    @files = []
    @file_list = []
    records = FileTransfer.all
    records.each do |record|
      record.files.each do |file_record|
        unless file_record.representable?
          next
        end
        @file_list << file_record
      end
    end
  end

  def create
    direction = 'up'
    # file_name = params[:file].filename
    file_name = 'annonymous file'
    file_transfer = FileTransfer.new(
      file_transfer_params.merge(direction: direction, file_name: file_name))
    if file_transfer.save
      flash[:success] = "File Transfer Record Created"
      redirect_to file_transfers_url
    else
      flash[:error] = 'File Transfer Record creation failed'
      render :new
    end
  end

  def new
    @file_transfers = FileTransfer.new
  end

  private
  def file_transfer_params
    params.require(:file_transfer).permit(:direction, :file_name, files: [])
  end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_transfers_helper.rb
module FileTransfersHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/views/file_transfers/index.html.haml
%div{class: "row"}
  - if @file_list.empty?
    %h1 Oops It appears you haven't uploaded anything yet!
    = link_to 'Upload', new_file_transfer_path, class: "btn btn-primary"
  - else
    - @file_list.each do |file|
      %div{class: "card m-5", style: "width: 22rem;"}
        %div{class: "view overlay"}
          = image_tag(file.representation(resize: '352x235'),
            class: 'img-fluid', alt: "#{file.filename.base}")
          %a{href: "#"}
          %div{class: "mask rgba-white-slight"}

        %div{class: "card-body"}
          %h4{class: "card-title"}
            = file.filename.base
          %p{class: "card-text"}
          =link_to('Download', rails_blob_path(file, disposition: 'attachment'),
            class: "btn btn-primary")

app/views/file_transfers/new.html.haml
%div{class: "row"}
  %div{class: "col-md-2"}
  %div{class: "col-md-10"}
    = form_for(:file_transfer, url: file_transfers_path, class: "form my-1") do |form|
      %div{class: "md-form"}
        %input{type: "hidden", name: "direction", value: "up"}
        %input{type: "text", name: "file_name", class: "form-control form-control-sm mr-sm-2 mb-0",
          placeholder: "File Name", aria: {label: "File Name"}}
        = form.file_field :files, multiple: true, direct_upload: true
        %button{type: "submit", class: "btn btn-primary btn-sm my-0"}
          Upload

app/views/landing_page/index.html.haml
%main{class: "mt-5"}
  .container
    / Grid row
    .row
      .col-md-5
        %h2 Keep your content synchronized
        %hr
        %p
          FileSync lets you keep you data synchronized so you can access
          it on any device. Pros:
        %p
          * Peace of mind. Your data is always safe
        %p
          * Ease of access. No matter how and where you created your data
          you can always access it from any device that have an Internet access
          by leveraging the power of the cloud
        =link_to 'Download', file_transfers_path, class: "btn btn-primary"
        =link_to 'Upload', new_file_transfer_path, class: "btn btn-primary"

      .col-md-7
        %div{class: "view overlay z-depth-1-half"}
          =image_tag 'nature.jpg', class: "card-img-top", alt: ""
          %div{class: "mask rgba-white-light"}

    / Grid row
    / Grid row
    .row
      / Grid column
      .col-lg-4.col-md-12
      / Grid column
      / Grid column
      .col-lg-4.col-md-6
      / Grid column
      / Grid column
      .col-lg-4.col-md-6
      / Grid column
    / Grid row
/ Main container

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:name=> "viewport", "content" => "width=device-width, initial-scale=1, shrink-to-fit=no"}
    %meta{:"http-equiv"=> "x-ua-compatible", "content" => "ie=edge"}
    %title FileSync
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      %nav{:class => "navbar navbar-expand-lg navbar-dark primary-color"}
        =link_to "FileSync", root_path, class: "navbar-brand"
        %button{class: "navbar-toggler",
          aria: {controls: "basicExampleNav", expanded: "false", label: "Toggle navigation"},
          data: {target: "#basicExampleNav", toggle: "collapse"}, type: "button"}
          %span{class: "navbar-toggler-icon"}


        %div{class: "collapse navbar-collapse", id: "basicExampleNav"}
          %ul{class: "navbar-nav ml-auto nav-flex-icons"}

            %li{class: "nav-item"}
              = link_to 'Upload', new_file_transfer_path, class: "nav-link"

            %li{class: "nav-item avatar dropdown"}
              %a{class: "nav-link dropdown-toggle", id: "navbarDropdownMenuLink-55",
                data: {toggle: "dropdown"},
                aria: {haspopup: "true", expanded: "false"}}
                =image_tag 'Madrid-dark-logo.png', class: "rounded-circle z-depth-0",
                  alt: "avatar image", size: '35x35'
              %div{class: "dropdown-menu dropdown-menu-right dropdown-secondary",
                aria: {labelledby: "navbarDropdownMenuLink-55"}}
                %a{class: "dropdown-item", href: "#"}Profile
                %a{class: "dropdown-item", href: "#"}Settings
                %a{class: "dropdown-item", href: "#"}Logout
    = yield